### ISSUE TITLE
Return type of exported function has or is using name 'UpsertAction'

### ISSUE THREAD

**Issue by moltar** [jawj/zapatos#10]
```ts
export async function createMigrationQuery(migration: s.migrations.Insertable) {
  return db.upsert('migrations', migration, 'id')
}
```

Getting the following TS error:

```
Return type of exported function has or is using name 'UpsertAction' from external module "/.../src/zapatos/src/shortcuts" but cannot be named.ts(4058)
```

**Comment by jawj** [comment]
Odd: I've not seen this error before. Can you put together a minimal test case for it?

Minor point: I don't think this function is actually async (you're not running the query here).

**Comment by moltar** [comment]
> Can you put together a minimal test case for it?

Sure, here you go: https://github.com/moltar/zapatos-issue-10

> Minor point: I don't think this function is actually async (you're not running the query here).

Yeah, it was an artifact of experimentation. It's not a real-world function. Otherwise ESLint would have picked it up and yelled at me :)

**Comment by jawj** [comment]
Brilliant, thanks for that. Just needed to export `UpsertAction` from `shortcuts.ts`. Not entirely sure there won't be other issues like this hiding somewhere, but fixed for now.

**Comment by moltar** [comment]
Thanks George!
