### ISSUE TITLE
Docs link 404

### ISSUE THREAD

**Issue by eyelidlessness** [jawj/zapatos#11]
In your docs' metadata section, it says:

> This document is generated from a [separate repository](https://github.com/jawj/zapatos-docs/).

When I click the link I get a 404 error. Is the repository private?

**Comment by eyelidlessness** [comment]
While I'm here, this is probably not worth opening another issue, but:

> It should test not just returned values but also inferred types — which is a little fiddly.

I don't know if it helps, but my approach to this has proven pretty solid:

```typescript
type Equals<X, Y> =
    (
        <T>() => T extends X ?
            1 :
            2
    ) extends
    (
        <T>() => T extends Y ?
            1 :
            2
    ) ?
        true :
        false;

const inferredThing = ... inferred thing ...;

const typesEqual: Equals<
    typeof inferredThing,
    {
        whatever: true,
    }
> = true;
// ^ This will error at compile time if the asserted type is not exactly the same

expect(typesEqual).toBe(true);
// ^ Not strictly necessary, but ensures `typesEqual` is referenced at runtime
```

**Comment by jawj** [comment]
Good catch: you’re right, I’d forgotten to make the docs repo public. Fixed now.

Thanks too for the testing hints.
