### ISSUE TITLE
Request: Docs for writing sql fragments that perform UPDATE operations.

### ISSUE THREAD

**Issue by maxweisel** [jawj/zapatos#116]
I'm trying to write a few update queries and I can't figure out how to do this kind of query in a type-safe manner:

```sql
UPDATE users SET display_name = 'max'
```

I'd really love to use `db.cols` and `db.vals` possibly like this:

```typescript
const user = {
  display_name: 'max',
}

db.sql<s.users.SQL, s.users.Selectable[]>`
  UPDATE ${'users'}
  SET (${db.cols(user}) = (${db.vals(user)})
`
```

However, it seems multi-column updates require sub-SELECT or ROW() expressions, so that's out.

I can write this:

```typescript
db.sql<s.users.SQL, s.users.Selectable[]>`
  UPDATE ${'users'}
  SET ${'display_name'} = ${db.param('max')}
`
```

Which compiles and properly type checks the column name `display_name` but not the type of the value being set on it. I can pass a `db.param(0)`, but I'd really love to enforce that the parameter matches the `display_name` property on `s.users.Updatable` which should require the value to be a string.

Max

**Comment by maxweisel** [comment]
It's worth mentioning that I'm aware of `db.update()` but the update query I'm trying to perform here requires something along the lines of `WHERE user_id = (SELECT user_id FROM platform_users WHERE platform_user_id = 'test')`, and I'm unaware how to make that work. I tried passing an SQLFragment inside of the Whereable which results in the bug I ran into over here: https://github.com/jawj/zapatos/issues/115

Max

**Comment by jawj** [comment]
Not sure I understand the problem with `ROW()` expressions in your first example. You should just be able to do:

```typescript
const author = { name: 'Jane Austen' };

await db.sql<s.authors.SQL, []>`
  UPDATE ${'authors'}
  SET (${db.cols(author)}) = ROW(${db.vals(author)})
`.run(pool);
```

But it's probably easier to use the `update` helper, either by using `self` in the appropriate place or more simply by just embedding the query:

```typescript
await db.update('authors', author, {
  id: db.sql<s.authors.SQL | s.books.SQL>`
    ${db.self} = (SELECT ${'authorId'} FROM ${'books'} WHERE ${'title'} = ${db.param('Pride and Prejudice')})`
}).run(pool);

/* OR */

await db.update('authors', author, db.sql<s.authors.SQL | s.books.SQL>`
  ${'id'} = (SELECT ${'authorId'} FROM ${'books'} WHERE ${'title'} = ${db.param('Pride and Prejudice')})
`).run(pool);
```

Does this fix the problem?

**Comment by maxweisel** [comment]
That's it! One quick question, could you use the `db.select` shorthand for the whereable in that second example? To be honest, I'd love to use those shortcuts instead of writing sql, but I couldn't quite figure out how to get the FROM query to work with another table.

One other question, I notice here you use `s.books.SQL` as the return type for the query, is there a reason it wouldn't be `s.books.Selectable[]`. I still don't fully understand why you'd use `.SQL` over `.Selectable[]` here.

Max

**Comment by jawj** [comment]
> One quick question, could you use the `db.select` shorthand for the whereable in that second example? To be honest, I'd love to use those shortcuts instead of writing sql, but I couldn't quite figure out how to get the FROM query to work with another table.

Yeah, I did try that, but it's not terribly elegant, since the shorthand function returns its result as JSON, so you have to pick the relevant column out (using `->` or `->>`) and then cast to the appropriate (non-JSON) type.

> One other question, I notice here you use `s.books.SQL` as the return type for the query, is there a reason it wouldn't be `s.books.Selectable[]`. I still don't fully understand why you'd use `.SQL` over `.Selectable[]` here.

The first type argument to `db.sql` is the _interpolations_ type: what's allowed within the `${}` the parts. The second argument (if one is passed — it's not necessary here) is the return type. Maybe have another look at [the docs on this](https://jawj.github.io/zapatos/#sql-tagged-template-strings).

**Comment by maxweisel** [comment]
> The first type argument to db.sql is the interpolations type: what's allowed within the ${} parts. The second argument (if one is passed — it's not necessary here) is the return type. Maybe have another look at [the docs on this](https://jawj.github.io/zapatos/#sql-tagged-template-strings).

Right, I'm aware of this, I guess the part I don't understand here is you passed `s.books.SQL` as the _return type_ here. I've only ever seen `s.books.Selectable[]` as a return type for a select query. There are no examples in the docs that use `s.books.SQL` as the _return type_ that I can find.

**Comment by tetchel** [comment]
@maxweisel if you're referring to this code:
![image](https://user-images.githubusercontent.com/8888438/170184686-b529b5a6-541a-45a5-803e-015abed64526.png)

jawj is not passing `s.books.SQL` as the return type, he's passing as part of a union for the interpolations type -
is it possible you misread: 
`s.authors.SQL | s.books.SQL` 
as 
`s.authors.SQL, s.books.SQL` 

?

**Comment by maxweisel** [comment]
Snap! I swear I read a comma there. Thanks for pointing that out!
