### ISSUE TITLE
cannot lateral join onto self as it references itself

### ISSUE THREAD

**Issue by purge** [jawj/zapatos#12]
SQL produced:

`select *, aa.id from a, lateral (select * from a where a.id = a.parent_id) aa`

(subselect where's itself.)

needs to produce something like:

`select *, aa.id from a, lateral (select * from a l1 where l1.id = a.promoted_from) aa`

**Comment by jawj** [comment]
I think you need [the `alias` option](https://jawj.github.io/zapatos/#lateral-and-alias)?

**Comment by purge** [comment]
oh yes, I really should've scrolled down a page where you explain this exact issue.
