### ISSUE TITLE
ROW() constructor causes update queries to fail

### ISSUE THREAD

**Issue by aekeus** [jawj/zapatos#121]
https://github.com/jawj/zapatos/blob/master/src/db/shortcuts.ts#L310 inserts a ROW constructor around the set of update variables. Execution of the generated query fails with the following error:

error: syntax error at or near "ROW"

Removing the ROW constructor fixes the error but seems to conflict with the comment at https://github.com/jawj/zapatos/blob/master/src/db/shortcuts.ts#L304

**Comment by jawj** [comment]
Can you share a reproducible test case (including the whole query), and tell us which version of Postgres (or CockroachDB, etc.) you're using? Thanks.

**Comment by jawj** [comment]
I'll reopen this if and when you come back with a test case and Postgres version.
