### ISSUE TITLE
Joining whereable object

### ISSUE THREAD

**Issue by alex88** [jawj/zapatos#124]
I'm building a `Whereable` object based on the http request fields. So my code looks like this:

```
const filters: table.Whereable = {};
if (dateFrom) {
  filters.createdAt = dateFrom;
}
```

all of that works however in another case I have to make a `OR` between two columns, so add a condition like `WHERE table.col_a = "foo" OR col_b = "bar"` along with the other conditions.
Is it currently possible? Without having to manuall concat multiple sql fragments?

**Comment by tetchel** [comment]
looks like this is similar to https://github.com/jawj/zapatos/issues/105

**Comment by alex88** [comment]
@tetchel oh yeah, basically that one, not exactly but I suppose the fix for that should fix this behavior as well, thanks!
