### ISSUE TITLE
Is it possible to pass NULL as a whereable?

### ISSUE THREAD

**Issue by maxweisel** [jawj/zapatos#125]
This is a simple example but I'm trying to do something like this:
```sql
CREATE TABLE games (
  -- Primary Key
  game_id varchar(36) NOT NULL
  PRIMARY KEY (game_id),
  
  winning_team integer -- Winning team index (0 or 1)
);
```

I want to update a game and set the `winning_team`, but only if `winning_team` is still set the default value of NULL:
```typescript
await db.sql<s.games.SQL, never>`
  UPDATE ${'games'}
  SET (${db.cols(gameUpdates)}) = ROW(${db.vals(gameUpdates)})
  WHERE ${{
    game_id: gameID,
    winning_team: null,
  }}
`.run(client)
```

However, if I try to pass null here it fails to match the type for `games.Whereable`. In theory I could pass `undefined` but that drops it from the where clause entirely. I was hoping there was something like a `db.null` but there's nothing I can find that works here.

`games.Whereable` for reference:

```winning_team?: boolean | db.Parameter<boolean> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, boolean | db.Parameter<boolean> | db.SQLFragment | db.ParentColumn>;```

Max

**Comment by jawj** [comment]
The right formula here is:

```sql
WHERE ${{
  game_id: gameID,
  winning_team: db.sql`${db.self} IS NULL`,
}}
```

And one of the (admittedly poorly-documented) conditions helpers makes this the friendlier. First, import them:

```sql
import { conditions as dc } from 'zapatos/db';
```

And then:

```sql
WHERE ${{
  game_id: gameID,
  winning_team: dc.isNull,
}}
```

**Comment by maxweisel** [comment]
Incredible. Thank you so much for the help! 🙏
