### ISSUE TITLE
Missing types in ESM project

### ISSUE THREAD

**Issue by petrovica** [jawj/zapatos#128]
Hi! 👋 

I had some issues importing zapatos on TS+ESM project. TypeScript complained `Could not find a declaration file...`. After some searching I found few sources pointing me to a solution:
https://github.com/typeorm/typeorm/issues/9075 (similar issue in TypeORM)
https://stackoverflow.com/a/72530967 (long answer)

I managed to fix it by forcing TypeScript to load `*.d.ts` files. Here's a diff, generated with [patch-package](https://github.com/ds300/patch-package) to patch `zapatos@6.0.1`.

Do you think you could integrate? :pray: 

```diff
diff --git a/node_modules/zapatos/package.json b/node_modules/zapatos/package.json
index f726e9e..04d5c8d 100644
--- a/node_modules/zapatos/package.json
+++ b/node_modules/zapatos/package.json
@@ -30,11 +30,13 @@
   "exports": {
     "./db": {
       "require": "./db.js",
-      "import": "./db.mjs"
+      "import": "./db.mjs",
+      "types": "./db.d.ts"
     },
     "./generate": {
       "require": "./generate.js",
-      "import": "./generate.mjs"
+      "import": "./generate.mjs",
+      "types": "./generate.d.ts"
     }
   },
   "keywords": [
```

Btw. thank you for your work on Zapatos :slightly_smiling_face:. I really enjoy using it :slightly_smiling_face:

**Comment by jawj** [comment]
Thanks, this looks like a simple addition, so it should be in the next release.

**Comment by petrovica** [comment]
Perfect, thank you very much :slightly_smiling_face:
