### ISSUE TITLE
RETURNING clauses only seem to allow for specific columns

### ISSUE THREAD

**Issue by AeroNotix** [jawj/zapatos#131]
Postgres allows for somewhat arbitrary expressions in RETURNING clauses.

...or is this in fact possible and I just didn't see / figure out how to do this?

**Comment by jawj** [comment]
Sorry for the slow reply. `returning` only allows an array of column names, but you can use the option `extras` to provide arbitrary SQL expressions. See https://jawj.github.io/zapatos/#extras.
