### ISSUE TITLE
Inconsistency between db.select and db.sql for date type

### ISSUE THREAD

**Issue by nomocas** [jawj/zapatos#146]
Hello All,

```sql
CREATE TABLE public.myTable (
    ...
    date date NOT NULL
    ...
}

INSERT INTO myTable(..., date, ...) VALUES(..., '2023-03-23', ...);
```

```typescript
db.select('myTable', {}).run(pool);  
//=> [{ ..., date: '2023-03-23', ... }]

// but

db.sql<myTable.SQL, myTable.JSONSelectable[]>`select * from ${'myTable'};`.run(pool);
// => [{..., date: 2023-03-22T23:00:00.000Z, ...}]
```
(Note that the second date is a js Date, and not a string - (printed as this because .toString()))

I would really prefer that both return a string (DateString).

Any idea ? :)

Info:
"typescript": "^4.9.5",
"zapatos": "^6.1.4"

**Comment by nomocas** [comment]
If we check `src/generate/pgTypes.ts` from zapatos source: we found: 

```typescript
const baseTsTypeForBasePgType = (pgType: string, enums: EnumData, context: TypeContext) => {
   // ...
    case 'date':
      return context === 'JSONSelectable' ? 'db.DateString' :
        context === 'Selectable' ? 'Date' :
          '(db.DateString | Date)';
   //...
};
```

And if we check how typescript is seeing the date in:
```typescript
const results = await db.sql<myTable.SQL, myTable.JSONSelectable[]>`select * from ${'myTable'};`.run(pool);
```
Typescript sees the date as a `DateString`, which is correct (because we ask some JSONSelectable). 
So the static typing is correct.

But at run-time it's a js date (and it should not).
```typescript
console.log(results[0].date instanceof Date); //=> true
console.log(results[0].date); //=> 2023-03-22T23:00:00.000Z
```

**Comment by jawj** [comment]
Using `JSONSelectable` in the type signature doesn't affect what will be returned — it just needs to match it.

You're not using any JSON functions to aggregate the results here, so you'll need:

```typescript
const results = await db.sql<myTable.SQL, myTable.Selectable[]>`select * from ${'myTable'};`.run(pool);
```

**Comment by nomocas** [comment]
Hello @jawj,

Thank you for your answers. Clearly I was missing something.

We managed to get what we want with something as :
```typescript
  ...
  const results = await db.sql<myTable.SQL, [{ result: myTable.JSONSelectable }]>`
  SELECT to_jsonb(${'myTable'}.*) as result
  FROM ...
  `.run(pool);
  return results.map((r) => r.result);
```
Which also works when results set is empty.

(Btw, thank you for this lib : we love it ;))

Cheers.

**Comment by jawj** [comment]
OK, great. And good to hear! :)
