### ISSUE TITLE
Importing generated enum values

### ISSUE THREAD

**Issue by jcassee** [jawj/zapatos#148]
For enums, Zapatos generates types like this:

```typescript
  export type my_enum = 'a' | 'b' | 'c';
  export namespace every {
    export type my_enum = ['a', 'b', 'c'];
  }
```

I would like to be able to access all possible enum values, for example to iterate over them. Apparently, my TypeScript-fu is not strong enough, because I was hoping to be able to access those `every.my_enum` values, but I cannot see a way to import them.

Is what I want possible? What would be the way to do so?

**Comment by jawj** [comment]
Zapatos generates types, not code. That means you can't directly access the enum values in code. But you can use the types to verify that the values in your code are correct and complete:

```typescript
import * as s from 'zapatos/schema';
const enumValues: s.every.my_enum = ['a', 'b', 'c'];
```

**Comment by jcassee** [comment]
That's already pretty nice. Thanks!
