### ISSUE TITLE
Table collision if names are the same from different schemas

### ISSUE THREAD

**Issue by moltar** [jawj/zapatos#15]
E.g. if you have two tables with the same name in different schemas they will collide in the `schema.ts` generated file.

**Comment by moltar** [comment]
In fact, when trying to build the TS files, get a lot of errors like:

```
src/infra/zapatos/schema.ts:92:13 - error TS2300: Duplicate identifier 'Table'.
src/infra/zapatos/schema.ts:93:13 - error TS2300: Duplicate identifier 'Selectable'.
```

Etc...

**Comment by jawj** [comment]
That's true: it's a [documented](https://jawj.github.io/zapatos/#configuration) limitation.

It might be nice to find a way round it, but I worry it will make things unpleasantly more complicated for the common use-case where everything's in `public`, and I currently have no need for it.

**Comment by jawj** [comment]
By the way, thanks for continuing to kick the tyres here. :)

**Comment by moltar** [comment]
> Note that schemas are not fully supported by Zapatos, since they are not included in the output types, but they will work by using Postgres’s search path if none of your table names is duplicated across different schemas.

But this doesn't appear to be the case.

I don't have any duplicated tables yet.

The errors I ran into above are from two different schemas with different table names.

> By the way, thanks for continuing to kick the tyres here. :)

Thanks for maintaining the package :)

**Comment by jawj** [comment]
Oh, OK. I have to admit I never actually tried it with multiple schemas, but I'm surprised you're getting these particular errors. I'll look into it when I have time.
