### ISSUE TITLE
typescript error import zapatos/schema

### ISSUE THREAD

**Issue by Kev1ntan** [jawj/zapatos#156]
hi, i got typescript error while import zapatos/schema. below is my tsconfig.json
```
{
  "compilerOptions": {
    "target": "ES2022",
    "module": "commonjs",
    "sourceMap": true,
    "outDir": "./build",
    "strictNullChecks": false,
    "typeRoots": ["./typings", "./node_modules/@types"],
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "types": ["node", "jest", "express"],
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "noEmitOnError": false,
    "strict": false
  },
  "include": ["**/*.ts"],
  "exclude": ["build", "node_modules", "test"]
}

```

Cannot find module 'zapatos/schema' or its corresponding type declarations.

please help, thanks.

**Comment by jawj** [comment]
Have you yet run `npx zapatos` to generate your typings?

You then need to make sure your Zapatos typings are included in the `include` path.

To make Zapatos work well, you need `"strictNullChecks": true`.

If it continues not to work, please post a repo I can take a look at to troubleshoot.
