### ISSUE TITLE
Generation is not idempotent because of time stamp

### ISSUE THREAD

**Issue by moltar** [jawj/zapatos#17]
This timestamp in `schema.ts` changes every time the generator is ran:

```
Generated using version 0.1.36 on 2020-05-31T08:35:33.497Z
```

I want to run the generator in CI and then make sure there are no changes (clean git state). This is to ensure that `zapatos` was ran in development, after any database schema changes. In other words to test for any deviation.

But this timestamp makes git state dirty and produces a diff.

Is the timestamp really necessary? Can we just get away with the version number?

The timestamp can be obtained from the filesystem anyways, if someone really needs it.

**Comment by jawj** [comment]
Thanks. Yes, I had pondered this myself. I'll remove it.
