### ISSUE TITLE
Add zapatos to postgres-benchmarks repo (all postgres node client)

### ISSUE THREAD

**Issue by cesco69** [jawj/zapatos#173]
https://github.com/porsager/postgres-benchmarks

**Comment by remidewitte** [comment]
Seemed a good idea :)

**Comment by cesco69** [comment]
I have seen zapatos is just a wrapper over "pg"... this mean a benchmark just show the amount of the overhead over pg

**Comment by remidewitte** [comment]
Indeed and so is slonik which is also listed.
