### ISSUE TITLE
Partial Upsert ?

### ISSUE THREAD

**Issue by jokesterfr** [jawj/zapatos#174]
Hi there!
thank you for this amazing lib, we are happy to use it here, at PrestaShop.

In our event-sourced code, we highly rely on the UPSERT SQL command, but would like to use zapatos upsert as a "partial" upsert of columns.

Thanks to the documentation, the `noNullUpdateColumns` is an option that can whitelist all the fields that won't be nulled by zapatos. In our case, all the columns are to be listed.

For code maintainance reasons, we would like to know if there is a simpler way, in the case we would like to whitelist all the updatable/insertable columns?

Thank you!

**Comment by jawj** [comment]
Sure, this looks like a nice enhancement. I think we could just have the the `upsert` shortcut accept `db.all` as a possible argument to `noNullUpdateColumns`.

**Comment by jawj** [comment]
Should be working in 6.4.1. Let me know if not!
