### ISSUE TITLE
JSON custom parsing for int8/bigint sometimes produces a `number` when it should produce a `string`

### ISSUE THREAD

**Issue by wrapperup** [jawj/zapatos#175]
Currently my use-case is storing Steam ID's in a database, though I've ran into an issue a few times where the ID returned by zapatos was a `number` type (instead of a string) for big numbers.

This can be reproduced by storing a number like `29007199254740991` (larger than `Number.MAX_SAFE_INTEGER`), which seems to sneak past this check:

https://github.com/jawj/zapatos/blob/b4314f5d9d5f4d55fba65673bbdd2dbd3f8cccf1/src/db/customJSON.ts#L16-L21

I've worked around it by adding a check that works for my case, but it would be nice to have a general fix since this check is defo not super sound for other applications.

**Comment by jawj** [comment]
Hmm, thanks for this report.

It's expected that numbers larger than `Number.MAX_SAFE_INTEGER` will be returned as `number` if that leaves them unscathed. So the `number | string` returned for an `int8` should always be fed to `BigInt()` or `String()`. (It has to work like this, because Zapatos doesn't know anything about the types behind JSON data at runtime).

But `29007199254740991` definitely **isn't** one of these numbers, because it ends up as `29007199254740990`. You're definitely seeing this behaviour with that number?

If so, I will certainly need to dig further. At first sight this should not be happening, because the string length is not `<= 15` and the output of `numericStringToExponential` (`'2.9007199254740991e+16'`) is not the same as `toExponential` (`'2.900719925474099e+16'`).

**Comment by wrapperup** [comment]
> But `29007199254740991` definitely **isn't** one of these numbers, because it ends up as a different number (`29007199254740990`). Can I confirm you're definitely seeing this behaviour with that number? (It didn't get changed on the way **in** to the database, for example?).

The actual number is the user's Steam ID which I can't share, but that number has the same issue. Insertion works just fine. In this case, the ID was correct in the database.

**Comment by jawj** [comment]
OK: I'll look into it.

**Comment by jawj** [comment]
Sorry, can I also just double-check you're calling `db.enableCustomJSONParsingForLargeNumbers(pg)` before you run your query?

**Comment by jawj** [comment]
A quick test has this working on my end:

```typescript
db.enableCustomJSONParsingForLargeNumbers(pg);

await (async () => {
  console.log('\n=== Issue #175 ===\n');

  const
    insertResult = await db.insert('int8test', { num: '29007199254740991' }).run(pool),
    selectResult = await db.selectOne('int8test', { num: '29007199254740991' }).run(pool);

  console.log('Both of these must be 29007199254740991 as string:');
  console.log({ insertResult, selectResult });
})();
```

Outputs:

```
=== Issue #175 ===

Both of these must be 29007199254740991 as string
{
  insertResult: { num: '29007199254740991' },
  selectResult: { num: '29007199254740991' }
}
```

Of course, **without** `db.enableCustomJSONParsingForLargeNumbers(pg)`, you get this:

```
=== Issue #175 ===

Both of these must be 29007199254740991 as string:
{
  insertResult: { num: 29007199254740990 },
  selectResult: { num: 29007199254740990 }
}

```

Are you calling `db.enableCustomJSONParsingForLargeNumbers(pg)`? Could you be accidentally casting to `number` somewhere after the result is returned? Or is there some other way I can recreate the problem?

**Comment by jawj** [comment]
Can you confirm here? I've not been able to reproduce the issue.

**Comment by wrapperup** [comment]
Seems like the issue is passing a large `number` to `BigInt`. Every large `number` that ends with a "0" seems to return as a number type from the parse function, but passing that number to `BigInt` produces a bad number.

```
RawId: 29007199254740990
Type: number
BigInt(RawId): 29007199254740992n
BigInt(RawId.toString()): 29007199254740990n
```

**Comment by jawj** [comment]
OK, I've made a change in 6.4.2 so that any integer outside the safe range is returned as a string. I think this should fix your case, but please do confirm.

Thanks for reporting this.
