### ISSUE TITLE
is it possible to do do OR where clauses with the select API?

### ISSUE THREAD

**Issue by jcoveney-anchorzero** [jawj/zapatos#178]
let's say I have a table with columns a, b, c that are all strings.

I have arrays arrA, arrB, arrC. I want to essentially do the following
```
SELECT *
FROM table
WHERE a in arrA AND (b in arrB OR c in arrC);
```
we like using the select API a lot, but I am struggling to get it working with this. doing the following is of course trivial
```
zapatosDb.select('table',
  {
    a: dc.isIn(arrA),
    b: dc.isIn(arrB),
    c: dc.isIn(arrC),
  });
```
but what I want is essentially
```
zapatosDb.select('table',
  {
    a: dc.isIn(arrA),
    ??? dc.or(b + dc.isIn(arrB), c + dc.isIn(arrC))
  });
```

I tried using dc.or with the whereables, but it didn't seem to work? that is to say
```
zapatosDb.select('table',
  dc.and({a: dc.isIn(arrA) }, dc.or({b: dc.isIn(arrB) }, {c: dc.isIn(arrC) }))
);
```
gave me an error. is it expected that that would work?

**Comment by jawj** [comment]
Try this:

```sql
const result = await db.select('table', 
  dc.and(
    { a: dc.isIn(arrA) },
    dc.or(
      { b: dc.isIn(arrB) },
      { c: dc.isIn(arrC) }
    )
  )
).run(pool);
```

**Comment by jcoveney-anchorzero** [comment]
I will investigate! we have slightly modified zapatos, and I think that that may be what's creating the issue here. thank you for the response! I will see if I can reproduce the issue in vanilla zapatos!

**Comment by jcoveney-anchorzero** [comment]
going to close this for now, we are going to work on this soon, I'll reopen if we can come up with a specific issue. thank you!
