### ISSUE TITLE
Propose to switch to using debug for output

### ISSUE THREAD

**Issue by moltar** [jawj/zapatos#18]
I think the output is too verbose.

https://github.com/jawj/zapatos/blob/f68666b4629f1f43964eec249019083fa622661f/generate/write.ts#L63

I think it would be good to switch to using the `debug` package. That way output can be enabled, if necessary, but would be silent by default.

Alternative solutions:

 * Allow to specify a custom logger (`node-pg-migrate` does this)
 * Add an env flag that disables (or enables) the output.

**Comment by jawj** [comment]
What the main part of the library already does is [allow functions to be passed in a config object, that receive different sorts of log messages](https://jawj.github.io/zapatos/#run-time-configuration).

When generating the schema programmatically, the obvious choice would be to do the same. That just leaves the question what the CLI tool should do. It's true that the UNIX way is to produce no output on success ... I don't know, let me mull this for a bit.

**Comment by jawj** [comment]
OK, this is addressed in 3d229eba60132cf9b4dd960626a6b5606a696763.

There's a new configuration key, `progressListener`, which accepts either a function (`(s: string) => void`) or the value `true` which behaves equivalently to `console.log` but is valid in a JSON configuration file.

If `progressListener` remains unset, nothing gets logged. Happy for me to close this now?

**Comment by jawj** [comment]
Hmm, just realised that warnings about missing type mappings still get logged to the console:

`* Postgres type "geometry" was mapped to TypeScript type "any"`

But, unlike the other messages, that's not really progress info, so perhaps it's legit.

**Comment by moltar** [comment]
The `setConfig` method comes from the generated code. But the `generate` itself runs from the library. How would it read the config from the locally generated singleton?

**Comment by jawj** [comment]
Right, there’s no need for `setConfig`/`getConfig`, since generation is one-shot, and anyway that code is in the wrong place, as you point out!

You just pass a (different) config object to the `generate` function, as seen in issue #7.

**Comment by jawj** [comment]
BTW I think I’ll also add a `warningListener` config option similar to the `progressListener` one, and have it default to `true` from the CLI.

**Comment by moltar** [comment]
Ah, okay, yup. Got it! Thanks

**Comment by jawj** [comment]
Right, I’ve finished this and documented it, so closing.

**Comment by jawj** [comment]
BTW, I've now [added a note](https://jawj.github.io/zapatos/#run-time-configuration) to the docs that shows how easy it is to wire the listeners up to the `debug` library, should you so wish.

**Comment by moltar** [comment]
Great, thanks!

This is how I am using it with `pino`:

```ts
// logger is an instance of pino
if (logger.isLevelEnabled('trace')) {
  const listener = (message: string) => logger.trace(message)

  db.setConfig({
    queryListener: listener,
    resultListener: listener,
    transactionListener: listener,
  })
}
```
