### ISSUE TITLE
The right problem

### ISSUE THREAD

**Issue by mrjjwright** [jawj/zapatos#19]
This lib has its eyes on the right problem with the right tools.   PostgreSQL meet TypeScript, TypeScript meet PostgreSQL.   PostgreSQL you are really good at describing SQL (and SQL is really good at describing data) so excited to have you here.   TypeScript you are really good at speaking schema as well aren't you and especially code  schema.    Both of you Postgres and TypeScript are extremely practical and well respected.  Wait, GraphQL wants to talk to us...nah, it will just confuse things, we have enough types as it is.

**Comment by mrjjwright** [comment]
Ok just ran the sample on my own schema, whoa, this is fire.

**Comment by jawj** [comment]
> Ok just ran the sample on my own schema, whoa, this is fire.

In a good way?

**Comment by mrjjwright** [comment]
yes in a good way!
