### ISSUE TITLE
Feature req: database.parent hints to reduce columns

### ISSUE THREAD

**Issue by moltar** [jawj/zapatos#21]
Would be great to be able to hint to `database.parent` to only show the column names of the table that we are joining on. E.g. via generics.

**Comment by moltar** [comment]
Thank you! :)

**Comment by moltar** [comment]
Oh, amazing, just realized that it is inferred from `columns` param, and don't even need to manually hint. Super duper! 👍 Thanks again.

**Comment by jawj** [comment]
Really? Can you show us an example? (I have to admit this is not intentional!)

**Comment by moltar** [comment]
![screenshot-2020-07-20_17-20-31-6GfgX5lm](https://user-images.githubusercontent.com/491247/87927472-720f9c00-caad-11ea-982b-7df3f134d23a.gif)

sorry for the giant gif :)

**Comment by jawj** [comment]
Ah, right. The columns `Pick`ed from the JSONSelectable are indeed driven by the `columns` option, and that should always have been true, though it's possible that some other recent fixes have made this work better.

What I did in the closing commit was make it possible to restrict the columns names made available in the call to the `parent` helper itself (i.e. here you could do `this.database.parent<this.schema.country.Column>('marketplace_country_code')`). So I think I misunderstood this issue entirely.

Glad to hear it's working well for you, anyway. :)

**Comment by moltar** [comment]
Wait ... no ... you are right. I misunderstood my own issue. You are totally right, this is what I meant. Duhh.
