### ISSUE TITLE
Type error in selectOne without TS strict mode

### ISSUE THREAD

**Issue by reiv** [jawj/zapatos#23]
There's a cryptic type error in `selectOne` that appears when `strict` isn't set to `true` in `tsconfig.json`.

```ts
Type '<T extends Table, C extends ColumnForTable<T>[], L extends SQLFragmentsMap, E extends SQLFragmentsMap>(table: any, where: any, options?: any) => SQLFragment<EnhancedSelectReturnTypeForTable<any, any[], E, SQLFragmentsMap>>' is not assignable to type 'SelectOneSignatures'.
  Type 'SQLFragment<EnhancedSelectReturnTypeForTable<any, any[], E, SQLFragmentsMap>>' is not assignable to type 'SQLFragment<EnhancedSelectReturnTypeForTable<T, C, L, E>>'.
    Type 'EnhancedSelectReturnTypeForTable<any, any[], E, SQLFragmentsMap>' is not assignable to type 'EnhancedSelectReturnTypeForTable<T, C, L, E>'.
      Type 'JSONSelectableForTable<any> | (E extends SQLFragmentsMap ? JSONSelectableForTable<any> & Lateral<E> : never)' is not assignable to type 'EnhancedSelectReturnTypeForTable<T, C, L, E>'.
        Type 'JSONSelectableForTable<any>' is not assignable to type 'EnhancedSelectReturnTypeForTable<T, C, L, E>'.ts(2322)
```

This error came up in a new project which didn't have a tsconfig yet. Since `strict` isn't the default, it might be worth mentioning somewhere - unless this could be fixed in a different way. It's weird, you'd expect `"strict": false` to result in *fewer* type errors, not the other way around ;-)

Not sure if the schema is relevant here - I removed the `strict` flag from zapatos' own tsconfig for comparison and the same error surfaced.

Typescript version: 3.9.6
zapatos version: 0.1.47

**Comment by jawj** [comment]
Can you pull and retry this? As it happens, I just came across and fixed a very similar-looking error while implementing `selectExactlyOne` (#20).

**Comment by jawj** [comment]
`npm install zapatos@latest` should work too, since 0.1.49 has the potential fix.

**Comment by reiv** [comment]
Can confirm, it works in `zapatos@latest` regardless of strict mode!

**Comment by jawj** [comment]
Great!
