### ISSUE TITLE
Enum array property is generated as any

### ISSUE THREAD

**Issue by PizzaPartyInc** [jawj/zapatos#27]
Hi!

It seems like enum arrays are currently not supported and generated properties will have and `any` type instead.

Reproduction steps:

```sql
DROP TYPE IF EXISTS app_public.random_enum CASCADE;
CREATE TYPE app_public.random_enum AS enum (
'TEST1',
'TEST2',
'TEST3'
);

DROP TABLE IF EXISTS app_public.random_assets CASCADE;
CREATE TABLE app_public.random_assets (
  id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  array_property app_public.random_enum[],
  single_property app_public.random_enum
);
```
zapatos will generate the following in schema.ts:

```ts
export type random_enum = 'TEST1' | 'TEST2' | 'TEST3';
export namespace every {
  export type random_enum = ['TEST1', 'TEST2', 'TEST3'];
}
//..........
export namespace random_assets {
  export type Table = 'random_assets';
  export interface Selectable {
    id: number;
    array_property: /* pg: _random_enum */ any | null;
    single_property: random_enum | null;
  }
  export interface Insertable {
    id?: number | DefaultType | SQLFragment;
    array_property?: /* pg: _random_enum */ any | null | DefaultType | SQLFragment;
    single_property?: random_enum | null | DefaultType | SQLFragment;
  }
//...........
```
Expected behavior - array_property to be something like this:

```ts
    array_property: random_enum[] | null;
    //......
    array_property?: random_enum[] | null | DefaultType | SQLFragment;
```

Additional info: 
Problem is probably in this function: https://github.com/jawj/zapatos/blob/363cfac0fc6291ca7207a75bbf6b7970f0fd99a2/generate/pgTypes.ts

There should probably be an additional check, that will remove `_` from pgType to check if it exists in enums object, and return pgType plus `[]` if original pgType started with `_`. Or maybe something more clever :)

**Comment by jawj** [comment]
Thanks, another good spot (and a chance to refactor the types mapping a bit, too). Can you confirm 0.1.52 fixes this for you?

**Comment by PizzaPartyInc** [comment]
Yep, looks good. Thanks! :)
