### ISSUE TITLE
How would you query SELECT FOR [NO KEY] UPDATE?

### ISSUE THREAD

**Issue by moltar** [jawj/zapatos#29]
Is there a good way to write the `SELECT FOR UPDATE` query?

Or should we just write a free-form query for these?

Feels like this could be a flag, or some other abstraction on the `select` method family.

Thoughts?

Reference: https://www.postgresql.org/docs/current/explicit-locking.html#LOCKING-ROWS

Thanks!

**Comment by jawj** [comment]
My first thought was that we could fix this using the composability of `SQLFragments`, like so:

```typescript
const
      baseQuery = db.selectOne("authors", { id: 123 }),
      lockingQuery = db.sql<db.SQL, ReturnType<typeof baseQuery.run>>`${baseQuery} FOR UPDATE`,
      result = await lockingQuery.run(pool);
```

This example works fine, even if`ReturnType<typeof baseQuery.run>` is not exactly elegant. 

But it fails if we `select` rather than `selectOne`, because then the JSON aggregate produces the error `FOR UPDATE is not allowed with aggregate functions.

I suspect the answer is a new option on `select` et al, probably called `lock`.

**Comment by jawj** [comment]
Two possibilities for a new option:

```
lock?: SelectLockingOptions[];
```

Where:

```typescript
export interface SelectLockingOptions {
  strength: 'UPDATE' | 'NO KEY UPDATE' | 'SHARE' | 'KEY SHARE';
  tables?: Table[];
  wait?: 'NOWAIT' | 'SKIP LOCKED';
}
```

Or otherwise simply:

```
lock?: SQLFragment;
```

And you can just write in a `db.sql` string with `FOR UPDATE` or whatever else yourself.

Since this seems like quite an advanced use-case, I might be tempted to keep it simple and go with the latter one. What do you think?

**Comment by moltar** [comment]
Why not both? :D

**Comment by moltar** [comment]
I really like the `SelectLockingOptions` interface approach.

But I am also worried about building in extra complexity into the core. It's a slippery slope. 

So I'll defer to your vision of the project.

**Comment by jawj** [comment]
Great. With your encouragement, and for consistency with the way we do `ORDER BY`, I've gone with the `SelectLockingOptions` approach. It's wasn't actually that complex, though I'm pretty sure I'm supporting a superset of the options that are currently needed. :)

I made a few tweaks to the key names I suggested above, and also to allow either single values or arrays of values in all relevant places.

In use, it looks like this:

```typescript
const
  authors1 = await db.select("authors", db.all, { lock: { for: "NO KEY UPDATE" } }).run(pool),
  authors2 = await db.select("authors", db.all, { lock: { for: "UPDATE", of: "authors", wait: "NOWAIT" } }).run(pool),
  // this next one is senseless but produces valid SQL
  authors3 = await db.select("authors", db.all, {
    lock: [
      { for: "UPDATE", of: ["authors", "books"], wait: "SKIP LOCKED" },
      { for: "SHARE", of: "tags" },
    ],
  }).compile();
```

Now I just need to document it and update the npm package ...

**Comment by moltar** [comment]
Thank you!
