### ISSUE TITLE
Writing WHERE column_name IN (value1, value2) queries

### ISSUE THREAD

**Issue by sahil87** [jawj/zapatos#30]
I tried searching the [docs](https://jawj.github.io/zapatos) for this but couldn't find anything. During the course of raising this issue I found a possible answer. 

The documentation indicated that `vals` was meant as a helper only for INSERT queries, so didn't use it in the first go. 

This is what I finally did:

```javascript
  const ids = [1,2]; //arbitrary values for the IN clause
  //trying to SELECT * FROM file WHERE id IN (1, 2)
  const getSomeFilesQuery = await db.sql<s.file.SQL, s.file.Selectable[]>`
    SELECT * FROM ${"file"}
    WHERE ${{
      id: db.sql<db.SQL>`${db.self} IN (${db.vals(ids)})`
    }}`;
```

In case this is the wrong approach, please do let me know.

**Comment by jawj** [comment]
Thanks for pointing this out. 

`vals` wasn't intended for use this way but, happily, it works and is safe (your id values above are properly interpolated as `$1`, `$2`, ...).

Two caveats, though: (1) it's a bit inefficient, and (2) if you have a lot of values, they'll get sorted in a surprising order (their indexes will get sorted as strings, so that index '11' appears before index '2', etc).

I might therefore streamline this in an upcoming update, and also make this usage 'official' in the docs.

**Comment by sahil87** [comment]
> I might therefore streamline this in an upcoming update, and also make this usage 'official' in the docs.

Thanks!

> One other note: if your use case is this simple, you'll probably be better off using the `select` shortcut, which is briefer and comes with fully typed results:

There are two reasons I didn't use shortcuts:
1. I was stuck with #31 (my fault entirely)
2. I am trying to come up with a single way for my team to write queries that scale to arbitrary complexity. We are shifting out of Hasura as an ORM - performance is becoming important now - trying to remove layers from between.

To your credit @jawj , this is the only project I found that:
* Uses SQL based schema as the source of truth. We are using [dbmate](https://github.com/amacneil/dbmate) for migrations btw.
* Produces Typescript types from the schema ([schemats](https://github.com/SweetIQ/schemats)) - and doing it in a way that we are free to use in other places (like the UI layer for API response type-checking) if needed.
* Sticks close to SQL. Completely agree with you that SQL is powerful, something that gets lost in complex ORMs like [sequelize](https://github.com/sequelize/sequelize/) or [typeorm](https://github.com/typeorm/typeorm)
* Provides a way to **write complex _SQL queries_ in a type-safe manner** (unlike [pg-typed](https://github.com/adelsz/pgtyped) in which I could only figure out simple queries)

Hoping to get this out in our production environment soon.

**Comment by jawj** [comment]
Good to hear why you picked this project: hope it continues to work well for you.
