### ISSUE TITLE
Add tags/releases

### ISSUE THREAD

**Issue by sahil87** [jawj/zapatos#32]
Would it be possible to add releases or tags to this repo so we could refer to this codebase in an idempotent manner via our package.json ?

Am assuming the specs here might change quickly. Tags/Releases will allow us to take our time updating queries.

**Comment by jawj** [comment]
Absolutely! I use `npm version` to publish, and I hadn't noticed that the tags it creates didn't get pushed. All previous versions are now tagged, and I've added a postversion hook to make this automatic in future.
