### ISSUE TITLE
Custom types

### ISSUE THREAD

**Issue by jawj** [jawj/zapatos#33]
It should be possible to supply custom TS type definitions to the schema generation process, both for actual custom types in pg (e.g. PostGIS geometry types) and for specific columns (e.g. jsonb columns with a known structure) by column name [+ table [ + schema]]).

**Comment by purge** [comment]
I worked around this by piping the generated schema through a custom typescript transformer to add my own types, but i'd definitely like to see more native support for it 👍

**Comment by jawj** [comment]
@purge Since you're the only other person I know to be using your own types, would you mind taking a look at what I've come up with here? (Anyone else is also welcome to chime in).

It's in the [custom-types](https://github.com/jawj/zapatos/tree/custom-types) branch, which I believe you can try out with `npm install jawj/zapatos#custom-types`.

In this new update, when an unknown type or [domain](https://www.postgresql.org/docs/current/sql-createdomain.html) is encountered during schema generation, a corresponding definition file is created under `./zapatos/custom`. This defaults to a simple type alias to `any` in the case of user-defined types, or the underlying type (if it's a known type) for domains. You can then customise this definition file as and when desired. It will not be overwritten during any future schema generations if already present.

Domain support means you can, for example, specify a particular JSON schema for a column or set of columns on the TypeScript side by creating a new domain as an alias to `json` or `jsonb` in Postgres.

There is a brief example of this in my try-out repo at https://github.com/jawj/zapatos-demo/tree/custom-types/zapatos/custom. `geometry` is a custom type from PostGIS (which gets cast to JSON), `mySpecialGeometry` is simply a domain that aliases it (not very useful here), and `mySpecialJsonb` is a domain aliasing `jsonb` (again, not yet made useful, but it shows what's generated by default).

**Comment by jawj** [comment]
@purge Any luck with this?

**Comment by purge** [comment]
sorry, not had time to get to this yet, i will be using some custom types next week though if you want to wait

**Comment by jawj** [comment]
OK, that's great: let us know how you get on. Having reflected on it, I think I'm pretty happy with the mechanism. 

My main source of doubt is the way the types are translated to TS, because I'm not sure there's any one right way to do this.

 Currently they're prefixed with `Pg`, the first character is upcased, and any invalid JS identifier characters are replaced with `_` (e.g. `geometry` -> `PgGeometry`). 

The reason for prefixing is to avoid problems with JS reserved words and invalid characters (e.g. digits) at the start of an identifier.

**Comment by jawj** [comment]
OK, I've now merged this stuff and released on npm as version 0.1.55. Feedback still welcome, though.

**Comment by purge** [comment]
great - i'll give it a look over once i stop fighting with google cloud. I think prefixing like that is perfectly acceptable.

**Comment by pdlug** [comment]
Can you provide an example of how to use this to provide a custom time for a `jsonb` column? I don't see anything generated in `src/zapatos/custom` for the `jsonb` columns I defined and it's not clear to me how to define this myself with the naming scheme outlined in this issue.

**Comment by jawj** [comment]
Sure. Yes, a plain Postgres `jsonb` column will just come out as the general `JSONValue` type in TypeScript.

To create a custom JSON subtype, you need to define a domain in Postgres:

```sql
CREATE DOMAIN "mySpecialJsonb" AS "jsonb";
```

Since you've done nothing else with the domain, it's effectively just a simple alias to `jsonb` on the Postgres side. 

Now use that in place of `jsonb` in your table definition. I think it should be safe to do:

```sql
ALTER TABLE "myTable" ALTER COLUMN "myExistingJsonbColumn" TYPE "mySpecialJsonb";
```

Now when you generate types, you'll get a custom type file to edit for `PgMySpecialJsonb`.

Sounds like I need to find somewhere to add this to the docs.

**Comment by pdlug** [comment]
Thanks for the details didn't think of using the actual domain. Any thoughts on how I might use this to handle a use case where the type is dependent on another field in the table? For example, I have a table of content items in a CMS-like use case, the `type` (`TEXT`) column determine what is acceptable in the `data` (`JSONB` custom domain) column. An alternative I suppose would be to put the type in the JSON data itself but there is a registry of types where it would be desirable to have this as a separate column.

**Comment by jawj** [comment]
Hmm. Probably no perfect answer here, but I guess if you were to duplicate the type in the JSON data then you could get type-checking that way?

**Comment by jawj** [comment]
I've updated the docs with approximately the above example now.

**Comment by moljac024** [comment]
I can't seem to find some guidance on using this with PostGIS and working with Geometry types, maybe I'm not looking right? Can you provide an example in the documentation?

**Comment by jawj** [comment]
Right — there's a small example in [the section on `extras`](https://jawj.github.io/zapatos/#extras), but that's about it. There might be some scope for creating a set of custom types designed for use with PostGIS (potentially alongside some custom casting rules).

How about you provide an example of what you're trying to do — using either Zapatos or just the plain `pg` library — and I'll take a look?

**Comment by moljac024** [comment]
At the moment I'm investigating a potential tech stack for a new project. We know we will use PostGIS but I don't have specific code examples at this time. I can definitely come back to this and post when I know more. What we know for sure is that we will need the ability to insert Geometry types and do some queries on those.

I would be ok with using zapatos for inserts and dropping down to pure SQL for querying if zapatos doesn't work out in that regard. Would that be possible?

Sorry if this is too high-level/abstract but I don't have more details at this time.

**Comment by jawj** [comment]
OK. I'm fairly sure you'll find Zapatos works nicely for this. It gives you full access to raw SQL, but can also help out with appropriate typing.

The [`extras` documentation linked above](https://jawj.github.io/zapatos/#extras) gives an example of querying, using the KNN operator, `<->`.

And I remembered that I've previously created and used custom types for PostGIS geometries too. Check:

* https://github.com/jawj/zapatos-demo/blob/aa37d6a6a27b5450bb7198af704c5e2953fb6487/demo.ts#L578
* https://github.com/jawj/zapatos-demo/blob/master/zapatos/custom/PgGeometry.ts

Do feel free to come back and ask questions/suggest improvements if you do go this way (perhaps under a new issue).
