### ISSUE TITLE
Typescript error when using shortcuts.ts - Property 'map' does not exist

### ISSUE THREAD

**Issue by sahil87** [jawj/zapatos#38]
![Screenshot from 2020-10-05 15-28-06](https://user-images.githubusercontent.com/9037064/95066032-78fa9200-071f-11eb-8751-f6e7ad3ecb45.png)

The code in [shortcuts.ts](https://github.com/jawj/zapatos/blob/v0.1.56/src/shortcuts.ts#L396) makes sense and is probably correct.
But Typescript doesn't understand that there never will be a scenario where `lock` isn't an array.

Luckily Zapatos copies its code outside node_modules - so for now I proceeded by adding a `// @ts-ignore` on line 396.
Logging here for reference.

**Comment by jawj** [comment]
That's odd, since it does get the type right for me:

<img width="1736" alt="Screenshot 2020-10-05 at 14 45 16" src="https://user-images.githubusercontent.com/141620/95087296-6b420e00-0719-11eb-8f91-5f33c9f9d0f6.png">

Is this related to #31? What version of TypeScript are you on, and do you have `strictNullChecks` turned on?

**Comment by PizzaPartyInc** [comment]
Had the same issue, zapatos version 0.1.56, typescript version 4.0.2, strictNullChecks are not even defined.

**Comment by jawj** [comment]
Thanks @PizzaPartyInc, and sorry about that. The issue actually arises when `strictNullChecks` is _not_ set, as established in #31.

I'm able to fix these issues in `shortcuts.ts`, and I'll make a release soon with those fixes. However, the deeper issue here is that type inference for `lateral` and `extras` in SELECT queries is also broken in the absence of `strictNullChecks` (that is, the relevant properties don't end up on the result type). I'll have a look at whether this if fixable, but I'm not sure it will be.

**Comment by jawj** [comment]
OK, I've released 0.1.57, which should fix the problems in `shortcuts.ts` when `strictNullChecks` are off. 

But I've also added notes to the docs that `strictNullChecks` are required in order for the `columns`, `lateral` and `extras` options to the `select` shortcuts to function.
