### ISSUE TITLE
Generating schema on a database without tables

### ISSUE THREAD

**Issue by PizzaPartyInc** [jawj/zapatos#41]
Hey :)

We have a minor problem in one particular use case. If we run zapatos against a database without tables, it will generate a non-buildable schema file:

![image](https://user-images.githubusercontent.com/37663061/95816587-24ab6f80-0d28-11eb-91d7-e3972f772043.png)

I understand this is not the case that is seen often, but was wondering if it can be handled.

Just to give an example, when a project is being set up, we hook zapatos to a migrations framework, and first thing we do is create an empty database and run a first migration with initial schemas and grants setup, which does not include any tables being created. At that point zapatos files are already being generated, but there are still no tables to generate the schema from :)

Thanks!

**Comment by jawj** [comment]
Huh, fair point. I've now updated the relevant logic to produce `never` when appropriate, as seen below, and released to npm as 0.1.59. 

Depending on your linting and TypeScript settings you may now get some complaints about unused variables, of course.

<img width="1033" alt="Screenshot 2020-10-13 at 10 45 43" src="https://user-images.githubusercontent.com/141620/95844897-6268c200-0d41-11eb-82d6-693c3819b682.png">

**Comment by PizzaPartyInc** [comment]
Thanks! Unused variables are acceptable, but I think some other places are not :(
Case with no tables. (with tables all is good)
![image](https://user-images.githubusercontent.com/37663061/95850525-a10a7680-0d59-11eb-92ff-ea5d472c08ec.png)

I tried changing `never` to `any` in those cases and it helped with all errors. Do you think it makes sense to use `any` in this case? (considering it's anyway a temporary state of schema that will be changed as soon as first table is added to database)

**Comment by jawj** [comment]
OK, I'll look at this again.

**Comment by jawj** [comment]
OK — I'm not wild about all these `any`s, because they mean that when the DB is empty a bunch of things won't be caught by the type system that could result in a runtime error.

But it seems like the lesser evil when weighed against source files that won't even compile, so this is what I've done for now, and release as 0.1.60.

**Comment by PizzaPartyInc** [comment]
I have tried to revisit this issue and submitted a new PR, details are described there :)
