### ISSUE TITLE
order exports in generated files

### ISSUE THREAD

**Issue by purge** [jawj/zapatos#47]
thought i'd get this in quick before you do a new major release:

The generated index file (zapatos/custom/index.ts) for custom type exports changes order for each database change for me (possibly due to the way pg exports them). It should be ordered alphabetically or something consistent.

**Comment by jawj** [comment]
Thanks. I would certainly fix that, except that in the upcoming version 3.0 there will be no `zapatos/custom/index.ts`!

(There will be a `zapatos/custom/index.d.ts`, but it won't contain anything that needs ordering).

You can find more details in PR #44.

Therefore, closing.

**Comment by jawj** [comment]
Actually, if you fancied testing what's in the `no-copy` branch and reporting back, that would be much appreciated! 

Best way is to checkout that branch and `npm link` it.
