### ISSUE TITLE
Publish library types

### ISSUE THREAD

**Issue by moltar** [jawj/zapatos#5]
Currently types are not emitted.

```
❯ tree node_modules/zapatos
node_modules/zapatos
├── LICENCE
├── README
├── dist
│   ├── generate-schema.js
│   ├── schema.js
│   └── src
│       ├── config.js
│       ├── core.js
│       ├── index.js
│       ├── pgErrors.js
│       ├── shortcuts.js
│       ├── transaction.js
│       └── utils.js
├── package.json
└── src
    ├── config.ts
    ├── core.ts
    ├── index.ts
    ├── pgErrors.ts
    ├── shortcuts.ts
    ├── transaction.ts
    └── utils.ts
```

**Comment by moltar** [comment]
Can do this now:

```ts
import {  } from 'zapatos/src'
```

**Comment by jawj** [comment]
Thanks for giving feedback. I'm sure this reflects only my incomplete knowledge of TypeScript, but I'm not wholly sure what publishing the types achieves — can you clarify this for me?

**Comment by moltar** [comment]
Usually the source files (`src/*.ts`) aren't published to NPM.

Only the transpiled JS files are published.

In which case, they do require the matching `*.d.ts` type declaration files to be available for consumption in TypeScript projects.

[There is a flag](https://www.typescriptlang.org/tsconfig/#declaration) in `tsconfig.json` that will emit declarations side by side with `.js` files.

In the case of this library, the workaround is to import from `zapatos/src` as I pointed out above. This works fine, but isn't a traditional solution.

**Comment by jawj** [comment]
Right, OK — because the library needs to be consumed as local .ts files in order to make use of the generated types in `schema.ts` (and is documented as such), I think this probably isn't all that helpful.

**Comment by moltar** [comment]
> because the library needs to be consumed as local .ts files

I am not sure what you mean.

Generally, if you publish a TS library to NPM, you want to publish types too.

When you consume the library from the TS project, the types get combined with generated JS code and everything just works. You don't need raw TS files to be published to NPM.

**Comment by jawj** [comment]
I may be wrong about this, but I think in this case things are different, because the library code has to import the DB schema that it has generated itself. See: https://jawj.github.io/zapatos/#how-do-i-use-it

**Comment by moltar** [comment]
I understand how zapatos works, I think. I've played around and read the docs.

But if #7 is a valid concern, then I think the import would be directly from `zapatos` and not from the generated code, right?

**Comment by jawj** [comment]
Right — as part of addressing #7, declarations are now emitted.
