### ISSUE TITLE
Importing from 'zapatos/schema' in files that are exculed in tsconfig.json

### ISSUE THREAD

**Issue by PizzaPartyInc** [jawj/zapatos#57]
Hey! :)

I finally got to the point of migrating to zapatos 3.1.1, but I stumbled on one slightly annoying problem. It's not a blocker, but maybe there is some easy way to avoid it that I have not thought about. :)

### Reproduction steps:

- Create a file with some explicit pattern, e.g. excluded.test.ts
- Add some contents to it with include from `zapatos/schema`
- Modify tsconfig to excluded this file, e.g.
```json
{
  "extends": "../../../tsconfig.be.json",
  "compilerOptions": {
    "strict": true,
    "noUnusedLocals": true,
    "noImplicitReturns": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "outDir": "./dist",
    "resolveJsonModule": true,
  },
  "exclude": ["node_modules", "dist", "**/*.test.ts"]
}
```
Have a look at excluded.test.ts
![image](https://user-images.githubusercontent.com/37663061/102060380-c61f7200-3dfa-11eb-8f3a-603d9b5090e8.png)

### Issue details
- The VScode cannot find the module. (I'm not sure if this is an issue with any other IDE)
- The code itself will work just fine.
- My exact use case 
   - we have tests which perform operations on real database (db that is created only for tests). These tests and related helper functions can utilize `zapatos/schema` types. (e.g. to cleanup content from test database or check that functions that are tested actually made proper modifications to db entities)
   - `tsconfig.json` is used by vscode and also excludes everything test-related, so that dist folder (generated by `yarn build` script) will only contain launchable project. files

### Current workaround
To use 2 tsconfig files
- tsconfig.json - used exclusively by VScode and excludes only `node_modules` and `dist` folders and it has all required compilerOptions
- tsconfig.build.json - used exclusively by `yarn build` script. It excludes `node_modules`, `dist` and everything test-related.
   - it extends the tsconfig.json, so all compilerOptions are inherited

Thanks!

**Comment by jawj** [comment]
I'm wondering if this is legitimate behaviour by VS Code or a bug to be reported.

Your current workaround sounds pretty reasonable. Would it work otherwise to add an explicit `/// <reference path="...">` at the top of each test file?

**Comment by PizzaPartyInc** [comment]
The problem with my workaround is that it only works for tests.
I found another case where I have a script file, which is executed using `ts-node`, and the same error happens there.
Adding the triple slash reference comment did not help me both with tests and scripts.
The only workaround for scripts I found is to use `--transpile-only` flag with `ts-node`, but that will not tell you about build errors that might actually matter, so I would prefer some cleaner solution...

**Comment by PizzaPartyInc** [comment]
Created an issue in typescript github, It has a link to a reproduction repo as well (without zapatos, but with same reproduction cases): https://github.com/microsoft/TypeScript/issues/42132

**Comment by jawj** [comment]
Thanks @PizzaPartyInc. Just looked at that issue thread. Do you think there's anything more that needs doing on the Zapatos side on this, or are you happy for me to close?

**Comment by PizzaPartyInc** [comment]
Yep, I think for now I'm fine with the workarounds. Closing the issue :)
