### ISSUE TITLE
Remove or replace postinstall echo

### ISSUE THREAD

**Issue by moltar** [jawj/zapatos#6]
`echo` only works on linux-like systems.

Alternatively can be replaced with a simply `.js` file that does `console.log`.

But I think maybe it is not necessary at all?

**Comment by jawj** [comment]
Huh, I tend not to think too much about Windows, but clearly this needs fixing.

I think it probably is helpful to remind people that they might need to regenerate the schema after an install or update, but I'll be sure to do it in a cross-platform way.

**Comment by moltar** [comment]
I guess you could do it like:

```
node -e "console.warn('Refresh yo!')"
```

**Comment by jawj** [comment]
Good idea. Implemented!
