### ISSUE TITLE
Zapatos in a Monorepo

### ISSUE THREAD

**Issue by sfsr12** [jawj/zapatos#60]
I struggled for a while with getting Zapatos working in a monorepo - but I figured it out, got it working, but have some slight points of friction that might be resolvable - or might already have known solutions that I couldn't find.

I made an example project to demonstrate and explain the issues I had.

https://github.com/sfsr12/zapatos-example

I think in the end it is just going to be issues with triple slash references since the fixes for #53 are probably going to fix the first issue I outline.

**Comment by jawj** [comment]
Thanks @sfsr12, this looks helpful.
