### ISSUE TITLE
BIGINT fields are presented as text

### ISSUE THREAD

**Issue by heyarne** [jawj/zapatos#63]
Thanks for creating an maintaining zapatos, much appreciated. :)

I ran across what I think is a bug.

Given the following database:
``` sql
CREATE TABLE "example" 
( "value" BIGINT );

INSERT INTO example VALUES (123456789);
```

Zapatos generates the following schema:
``` js
// ...
  /* --- tables --- */

  export namespace example {
    export type Table = 'example';
    export interface Selectable {
      example_value: string | null;
    }
// ...
```

What's interesting is that this reflects upstream behavior of the `pg` module. Running the following nodejs code: 
``` js
client.query('SELECT * FROM example;')
```
Produces the following result:
```
Result {
  command: 'SELECT',
  rowCount: 1,
  oid: null,
  rows: [ { example_value: '123456789' } ],
  fields: [
    Field {
      name: 'example_value',
      tableID: 16384,
      columnID: 1,
      dataTypeID: 1043,
      dataTypeSize: -1,
      dataTypeModifier: -1,
      format: 'text'
    }
  ],
  _parsers: [ [Function: noParse] ],
  _types: TypeOverrides {
    _types: {
      getTypeParser: [Function: getTypeParser],
      setTypeParser: [Function: setTypeParser],
      arrayParser: [Object],
      builtins: [Object]
    },
    text: {},
    binary: {}
  },
  RowCtor: null,
  rowAsArray: false
}
```

This should probably instead be handled as a native [`BigInt`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#bigint_type)?

**Comment by heyarne** [comment]
Oh sorry my bad, I got confused about the role of zapatos when using it in another project! I might reopen this later when investigating another bug that I'm hitting.

**Comment by jawj** [comment]
OK! Yes, it's probably not Zapatos' job to change behaviour of the underlying pg library.

**Comment by TheNickmaster21** [comment]
Should the expected behavior be that BIGINT columns are strings (to match pg)? When I generate typings for my schema, I get number types for BIGINT fields that are returned as strings by pg.

**Comment by rsparkyc** [comment]
This would seem to make sense, especially since bigints that postgres supports are larger than the javascript numeric type.

**Comment by TheNickmaster21** [comment]
I would love to see this changed so we do not have to manually install a tgz file in our repository. 😄  I have created a pull request with the change: https://github.com/jawj/zapatos/pull/68

Alternatively, even if there was a setting to set the type of int8s to string, that would be great but it seems, at least to me, that the correct behavior is to actually match the datatypes being returned by pg.
