### ISSUE TITLE
[Feature Request] upsert many using writable CTE

### ISSUE THREAD

**Issue by xiaoyu-tamu** [jawj/zapatos#65]
Is it possible to support update multiple row in a type-safe way?

This would allow user to upsert one, upsert many without increment sequence id and it could also make update many with different condition possible

Something like this

```sql
      with data as (
        -- unnest data
        -- SELECT bar, baz FROM unnest($1::int4[], $2::text[]) AS foo(bar, baz)
      ),
      updated AS (
        UPDATE ...
        SET ...
        FROM data
        WHERE ...
        RETURNING ...
      ),
      created AS (
        INSERT INTO table (cols)
        SELECT ...
        FROM data 
        WHERE NOT EXISTS (
          SELECT 1 FROM updated WHERE ...
        )
        RETURNING ...
      )
      SELECT * FROM updated 
      UNION ALL
      SELECT * FROM created
```

**Comment by jawj** [comment]
Can you spell out in a bit more detail what this is supposed to do, and maybe include an example of when it would be useful? 

At a glance it looks rather like an unusual way of doing an upsert (i.e. `INSERT ... ON CONFLICT ... DO UPDATE ...`), which is [already supported](https://jawj.github.io/zapatos/#upsert).

**Comment by xiaoyu-tamu** [comment]
Yeah, it basically just `INSERT ... ON CONFLICT ... DO UPDATE ...```.  

But doing `ON CONFLICT ... DO UPDATE .. ` will increase the sequence number, it will leave a huge gap if upsert large amount of data. The next time I insert new data,  it is thousands of numbers above my last value. 

my use case would be sync data to postgres from an external resource every hour, if doing `insert on conflict do update`, the data may looks like this

```
ID             NAME
1               apple
10000      pear
50000     orange
```

**Comment by jawj** [comment]
I wonder if your alternative formulation guarantees atomicity [the same way the native functionality does](https://wiki.postgresql.org/wiki/UPSERT)?

I don't want to implement this in the core library, but you're of course free to either write and type the queries manually with ``` db.sql`...` ```, or indeed to write your own shortcut function.
