### ISSUE TITLE
Improve function interfaces, put the rest into an options object

### ISSUE THREAD

**Issue by xiaoyu-tamu** [jawj/zapatos#66]
I think the current implementation of update/upsert using position argument may not very clear.  User may accidentally put `whereable` and `updatable`  in wrong order. 

```ts
// mean to update listing set id to 1 where id = 2

 await db
        .update('listing', {id:1}, {id:2}, { returning: ['id'] })
        .run(pool)

// if we accidentally switch the order, it's a different query, and it's hard to find out since typescript not complaint.

 await db
        .update('listing', {id:2}, {id:1}, { returning: ['id'] })
        .run(pool)
```

I suggest we should put the rest into an options object in next major version.

```ts
// from this
db.update('bankAccounts',
      { balance: db.sql`${db.self} - ${db.param(amount)}` },
      { id: sendingAccountId }
      { returning: ['id']},
);


// to this
db.update(
  'bankAccounts',
  {
     data: { balance: db.sql`${db.self} - ${db.param(amount)}`  }
     where : { id: sendingAccountId })}
     returning: ['id']
  }
)



// or maybe this
db.update(
  {
     table: 'bankAccounts',
     data: { balance: db.sql`${db.self} - ${db.param(amount)}`  }
     where : { id: sendingAccountId })}
     returning: ['id']
  }
)
```

**Comment by jawj** [comment]
This is true — I have once or twice made the same mistake myself.

However, I'm not sure I like the alternatives that much, and they'd be a big backwards-incompatible change, so I'm inclined to leave things as they are.

I'll leave this open for a bit in case anyone else has strong opinions they want to share.

**Comment by jawj** [comment]
Since we've gone a month with no strong opinions expressed, I'm going to put this one to bed for now.
