### ISSUE TITLE
[Question] Return dates as Date and not string (Selectable instead of JSONSelectable)

### ISSUE THREAD

**Issue by Yann-P** [jawj/zapatos#67]
I would like to integrate zapatos into my project that only uses `node-pg`.

The integration is seamless, however I have one issue with dates being returned as string which is not `node-pg`'s behavior.

```
export const insertMyTable = async (
  pool: Pool,
  row: my_table.Insertable,
): Promise<my_table.Selectable> => db.insert('my_table', row).run(pool);
```

I have error `Type string is not assignable to Date` for one column of my_table.

Is there a way to make `insert` return a `Selectable` instead of a `JSONSelectable` ?

**Comment by jawj** [comment]
The `select` queries have to return dates as strings because they use make heavy use of Postgres' JSON functions, and of course there's no native date type in JSON.

I decided it was the lesser of two evils to make all the shortcut functions consistent, so they all do the same.

**Comment by Yann-P** [comment]
Ok, that's fair
I just wanted to make sure I didn't miss a flag or something.

Thanks for your answer
