### ISSUE TITLE
Question and possible bug: upsert does not compile to a validate sql statement

### ISSUE THREAD

**Issue by seanyu4296** [jawj/zapatos#71]
Hi,

Firstly thanks for creating this library coming from statically typed FP languages and not liking ORM, i found this project really cool. I'm now trying to use it in a fun side project.

I am using zapatos v3.3.0

I tried using the `upsert` function for brevity sake here is a snippet
```
 console.log(
    db
      .upsert(
        "chat",
        {
          telegram_chat_id: "test_id",
        },
        "telegram_chat_id"
      )
      .compile()
  );
```
but it seems to create an invalid sql statement
```
INSERT INTO "chat" ("telegram_chat_id") VALUES ($1) ON CONFLICT ("telegram_chat_id") DO UPDATE SET () = ROW() RETURNING to_jsonb("chat".*) || jsonb_build_object('$action', CASE xmax WHEN 0 THEN 'INSERT' ELSE 'UPDATE' END) AS result
```
Not sure if the mistake is the missing `DO UPDATE SET ("telegram_chat_id") = ROW("telegram_chat_id")` but i am also not sure if it is caused by my db schema

@jawj do you have some ideas on what might be wrong? or how to debug it? Pointers on how I can debug it myself is welcome :) 

DB schema is: 
```
-- migrate:up
create table question (
  id serial primary key,
  content text not null,
  "created" TIMESTAMPTZ NOT NULL DEFAULT (now()),
  "updated" TIMESTAMPTZ NOT NULL DEFAULT (now())
);

create table chat (
  telegram_chat_id varchar(100) primary key,
  "created" TIMESTAMPTZ NOT NULL DEFAULT (now()),
  "updated" TIMESTAMPTZ NOT NULL DEFAULT (now())
);
```

I used `dbmate` to run the migration script

**Comment by jawj** [comment]
Huh, I guess you could call this a bug. Since the only column being upserted is the one on which a conflict is to be recognised, this is really an `ON CONFLICT ... DO NOTHING` query, and I guess we should recognise it (and generate it) as such.

**Comment by jawj** [comment]
Hmm, this turns out to be a bit thorny, because a `DO NOTHING` causes nothing to be returned ...

https://dba.stackexchange.com/questions/129522/how-to-get-the-id-of-the-conflicting-row-in-upsert?newreg=73012b692b4f484d8406e4f67dd98ea6
https://stackoverflow.com/questions/34708509/how-to-use-returning-with-on-conflict-in-postgresql/42217872#42217872

**Comment by jawj** [comment]
I started implementing the `WITH "x" AS (/* upsert query */) UNION SELECT * FROM "table" WHERE /* conflicting columns equal upsert columns */` strategy outlined in the links above. 

But this falls apart when the conflict target is an index, because we don't know what columns to match on.

For now, a workaround to your issue is to set the conflict target as the index — i.e.

```typescript
await db.upsert("chat", { telegram_chat_id: "test_id" }, db.constraint("chat_pkey")).run(pool);
```

This works fine, presumably at the expense of rewriting an identical row in case of conflicts.

I'll have a bit more of a think about what to do about this in general. We might need a new option that writes a `DO NOTHING` query and adds `null` to the possible result types.

**Comment by jawj** [comment]
Oh, hang on, no it doesn't fall apart because — as I just explained — it's not needed when the conflict target is an index! Sorry for the blow-by-blow account here. I'm going to try the `WITH "x" AS (/* upsert query */) UNION SELECT * FROM "table" WHERE /* conflicting columns equal upsert columns */` strategy again ...

**Comment by jawj** [comment]
OK, it probably needs a bit more testing, but I think I have the answer. The version now in `master` generates the following for your example:

```sql
WITH base AS (
  INSERT INTO "chat" ("telegram_chat_id") VALUES ($1)
  ON CONFLICT ("telegram_chat_id") DO NOTHING
  RETURNING to_jsonb ("chat".*) || 
    jsonb_build_object('$action', CASE xmax WHEN 0 THEN 'INSERT' ELSE 'UPDATE' END) AS result
)
SELECT * FROM base
UNION
SELECT to_jsonb ("chat".*) || '{ "$action": "NOTHING" }' AS result
FROM "chat"
WHERE ROW ("telegram_chat_id") IN (ROW ($2))
```

And this result:

```javascript
{
  '$action': 'NOTHING',
  created: '2021-02-15T22:30:15.017572+00:00',
  updated: '2021-02-15T22:30:15.017572+00:00',
  telegram_chat_id: 'test_id'
}
```

**Comment by seanyu4296** [comment]
Thanks so much @jawj for looking into this! 

I think i get the problem more now. I am still working on having in depth knowledge and more experience with SQL in general.

Read through https://www.postgresql.org/docs/current/sql-insert.html#SQL-ON-CONFLICT, so its a rule in `UPSERT` that we give `ON CONFLICT` columns that have a `UNIQUE` constraint or an index. Does `zapatos` enforce constraints/type infer which columns have `UNIQUE` or have an index?

How do i use the current `master` in my ts project?

**Comment by jawj** [comment]
Right now, I suggest you work around the issue by specifying the index rather than the column as the conflict target (as demonstrated above). I'll include this change when I next make a release.

**Comment by seanyu4296** [comment]
Does zapatos enforce constraints/type inference which columns have UNIQUE or have an index? @jawj

**Comment by jawj** [comment]
If I understand you right, yes — once you put in `db.constraint`, VS Code should list the valid index names for you to choose.

<img width="1115" alt="Screenshot 2021-02-16 at 17 27 58" src="https://user-images.githubusercontent.com/141620/108099382-6f454b80-707c-11eb-9c78-a7f82d3488e8.png">

**Comment by seanyu4296** [comment]
Given a table with 
```sql
create table chat (
  id serial primary key,
  telegram_chat_id varchar(100), -- no unique constraint or index
  "created" TIMESTAMPTZ NOT NULL DEFAULT (now()),
  "updated" TIMESTAMPTZ NOT NULL DEFAULT (now())
);
```


```
await db.upsert("chat", [{ telegram_chat_id: "test_id"}], ["telegram_chat_id"]).run(pool)
```
i think zapatos allows the below right which should actually be invalid since `telegram_chat_id` is neither an index nor a unique field 

@jawj

**Comment by seanyu4296** [comment]
On a side note, do you have resources or tips on how to understand how you leveraged typescript's type system in zapatos? it is pretty advanced and i'm actually curious how things

**Comment by jawj** [comment]
> i think zapatos allows the below right which should actually be invalid since `telegram_chat_id` is neither an index nor a unique field 

You're right, if you specify the index Zapatos checks it, but if you specify the column(s) it doesn't check that there's an index on them. Of the top of my head I'm not sure how easy or difficult that would be.

**Comment by jawj** [comment]
> On a side note, do you have resources or tips on how to understand how you leveraged typescript's type system in zapatos? it is pretty advanced and i'm actually curious how things work  @jawj 

Not at present. Most of the advanced stuff is in `shortcuts.ts`. You can start with this function signature and work backwards:

```typescript
export interface SelectSignatures {
  <T extends Table,
    C extends ColumnsOption<T>,
    L extends LateralOption<C, E>,
    E extends ExtrasOption,
    M extends SelectResultMode = SelectResultMode.Many
    >(
    table: T,
    where: WhereableForTable<T> | SQLFragment | AllType,
    options?: SelectOptionsForTable<T, C, L, E>,
    mode?: M,
  ): SQLFragment<FullSelectReturnTypeForTable<T, C, L, E, M>>;
}
```

**Comment by jawj** [comment]
BTW on the original issue, I think I may have way over-complicated the fix, and when I have a moment to redo it the right answer was probably just to stop trying to exclude the conflict target columns from the `UPDATE` branch.

Time is at a premium right now with the kids' schools closed ...

**Comment by jawj** [comment]
OK, I've reverted the earlier change and simplified `upsert` so that it no longer makes an effort to avoid updating the conflict target columns. This fixes the invalid query that was being issued for your usage, and I don't think it will significantly affect performance for the more normal case where there are non-conflict-target columns also involved (since I believe an `UPDATE` always rewrites the whole row anyway).

The only slight disadvantage of this approach is that in your case it rewrites a row unnecessarily. I think the answer here is to introduce a new shortcut for `INSERT ... ON CONFLICT DO NOTHING`, which I'll get to one of these days.

Your query now looks like this:

```sql
INSERT INTO "chat" ("telegram_chat_id") VALUES ($1) 
ON CONFLICT ("telegram_chat_id") DO UPDATE SET ("telegram_chat_id") = ROW(EXCLUDED."telegram_chat_id") 
RETURNING to_jsonb("chat".*) || jsonb_build_object('$action', CASE xmax WHEN 0 THEN 'INSERT' ELSE 'UPDATE' END) AS result
```

Again, this will go in the next release.

**Comment by jawj** [comment]
BTW, in 3.4 you can now specify `{ updateColumns: [] }` to make this an `ON CONFLICT ... DO NOTHING` query and not rewrite the row.

**Comment by seanyu4296** [comment]
Sorry for the late reply @jawj been swamped with personal and day job responsibilities. On a side note, I saw your personal website, and its incredible on how you manage to be a great coder, CTO, a senior lecturer on economics. How do you do it?

> You're right, if you specify the index Zapatos checks it, but if you specify the column(s) it doesn't check that there's an index on them. Of the top of my head I'm not sure how easy or difficult that would be.
I see i see is this feature desirable? 

> Not at present. I guess this could be a good topic for a future blog post. The key principle is heavy and nested use of generics, conditional types, and indexed access types. Most of the advanced stuff is in shortcuts.ts. You can start with this function signature and work backwards:

Gotcha typescript type system really is quite interesting. I'll try to grok it soon been looking into conditional types this week actually

Thanks again so much @jawj will try the upsert later today

**Comment by jawj** [comment]
> > You're right, if you specify the index Zapatos checks it, but if you specify the column(s) it doesn't check that there's an index on them. Of the top of my head I'm not sure how easy or difficult that would be.
> 
> I see i see is this feature desirable? Are there alot of complications to it?

On thinking about it some more, I don't think this is possible, since an index can be on any expression.
