### ISSUE TITLE
prepared statements

### ISSUE THREAD

**Issue by puckey** [jawj/zapatos#78]
I am porting over a complex query where I was using prepared statements previously to improve its performance.

`node-postgres` allows this simply by adding a `name` property to the `queryConfig` [object](https://node-postgres.com/features/queries#query-config-object).

```js
const query = {
  // give the query a unique name
  name: 'fetch-user',
  text: 'SELECT * FROM user WHERE id = $1',
  values: [1],
}
```

To do this with zapatos I would need to:

```js
const query = db.sql`select * from somewhere`;
const compiled = query.compile();
compiled.name = 'test';
return (await pool.query(compiled)).rows;
```

Would it be an idea to allow prepared statements in zapatos in without having to escape to `node-postgres`?

We could do so through a `.name = 'name'` or `.preparedStatement= 'name'` property on `db. SQLFragment`:

```js
const query = db.sql`select * from somewhere`;
query.name = 'name';
return q.run(pool);
```

or through a more general `compileTransform` function property which would allow editing the compiled query:

```js
const query = db.sql`select * from somewhere`;
query.compileTransform = (query) => {
    query.name = 'name';
};
return q.run(pool);
```

or by adding a config object to run:

```js
db.sql`select * from somewhere`.run(pool, { name: 'name' });
```

**Comment by jawj** [comment]
Your last suggestion — the config object — is probably simplest to implement, and pleasantly concise in use.

On the other hand, I guess the name is really a property of the query rather than a given execution of it.

So I think I'll go for:

```typescript
const query = db.sql`select * from somewhere`;
query.name = 'name';
return q.run(pool);
```

But I might also add a convenience function for easy chaining, so we can have things like:

```typescript
const query = db.sql`select * from somewhere`.named('name').run(pool);
```

**Comment by puckey** [comment]
Great!

I was just wondering if there is a way to escape the need to give these a name. Would a hashed version of the generated sql suffice? Something like `name: require('crypto').createHash('sha1').update(data).digest('base64');`

This would allow for something like `const query = db.sql`select * from somewhere`.prepared().run(pool);`

**Comment by jawj** [comment]
Hmm, I like that idea. I guess the `prepared` method could take an optional name, and if one's not given it can use a hash (or possibly simply an increasing sequence: `_zapatos_1`, `_zapatos_2`, etc).

**Comment by puckey** [comment]
Indeed, there is no need for a hash. Much better with a sequential key.

**Comment by jawj** [comment]
OK, the `master` branch now has a `prepared()` method on `SQLFragment` that behaves as suggested above.

Are you able to try this and see if it does what you need, by using the current version on `master`? (Clone zapatos next to your repo, `npm install`, `npm build`, and `npm link`. Then `npm link zapatos` within your repo).

**Comment by puckey** [comment]
Fantastic – I tested it and it works. Thanks again!

**Comment by jawj** [comment]
Great — thanks. Should be in the next release, then.
