### ISSUE TITLE
Dependency cycle detected

### ISSUE THREAD

**Issue by moltar** [jawj/zapatos#8]
ESLint raises an error (`import/no-cycle`) on generated code:

```ts
import {
  ColumnNames,
  ColumnValues,
  DateString,
  DefaultType,
  GenericSQLExpression,
  JSONArray,
  JSONValue,
  ParentColumn,
  SQL,
  SQLFragment,
} from './src/core'
```

I think if you only need types then better to import as types:

```ts
import type { ... } from './src/core'
```

**Comment by jawj** [comment]
I don't think this is a harmful cycle, but I will have a look whether `import type` would fix it.

**Comment by jawj** [comment]
Hi there. I'm now using `import type` where possible and have eliminated a circular dependency between `transaction.ts` and `core.ts`. I don't think it's possible to eliminate the circular dependency between `schema.ts` and `core.ts`, but I also don't think it does any harm.

Perhaps I should add an `/* eslint-disable */` in all the source files (I previously had `/* tslint-disable */` in there, though I just removed it as part of fixing this ...).

**Comment by jawj** [comment]
As of v0.1.39 I'm now writing an `.eslintrc.json` file into the generated `zapatos` directory, to suppress linting of the Zapatos files within other projects (which may fail, since we don't know what rules will be applied).
