### ISSUE TITLE
Question: how to search in arrays

### ISSUE THREAD

**Issue by filipecatraia** [jawj/zapatos#83]
Hey George!

I'm really happy with Zapatos! We finally have the right balance between type safety and something that works as expected.

I do feel a bit dumb about the question, but I gotta ask: what would the query be for searching an array? I'm trying to convert a conventional array search into a Zapatos-worthy template string, to no avail:

```sql
SELECT *
  FROM ${'myTable'}
  WHERE '${valueToLookFor}' = ANY (${'columnWithVarcharArrays'})
  LIMIT 1
```

I've tried to wrap `valueToLookFor` in `db.vals`, for example. The query compiles to `... WHERE '$1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11'`, trying to replace each char in `valueToLookFor` as a positional parameter. 

I also gave the other syntax from the [Postgres docs](https://www.postgresql.org/docs/current/arrays.html) a shot, but get an operand error:

```sql
SELECT * FROM sal_emp WHERE pay_by_quarter && ARRAY[10000];
```

I saw the Zapatos docs mention something about issues with `jsonb` and how parameters get cast, but I'm not sure that's a related problem.

Any tips to help me out?

Thanks a million!

**Comment by filipecatraia** [comment]
Okay, so I made it work. My IDE offered `db.raw` as a completion and I gave it a shot:

```sql
... WHERE '${db.raw(valueToLookFor)}' = ANY (${'columnWithVarcharArrays'})
```

This works because the `valueToLookFor` is replaced by the variable's value and gets neatly wrapped in the double `'` around it! Not sure if this is the best approach.

One thing this made me notice, is that the docs might benefit from being split into multiple pages, because a search for (e.g.) `array` isn't very helpful unless you skip a lot of false positives :) Just a thought.

**Comment by jawj** [comment]
First: be careful using `db.raw`. If `valueToLookFor` can be controlled by the user, you're now vulnerable to SQL injection attacks. (Plus, if it ever contains a quote character, you have a SQL error).

I think you just want `db.param` here? That is:

    WHERE ${db.param(valueToLookFor)} = ANY (${'columnWithVarcharArrays'})

**Comment by filipecatraia** [comment]
Interesting, that works, if I remove the `'` surrounding the value. Otherwise I get:

```
bind message supplies 1 parameters, but prepared statement "" requires 0
```

But alright, your solution is even better! Thanks a lot!
