### ISSUE TITLE
Add option for exported types to be type synonyms not interfaces

### ISSUE THREAD

**Issue by RigoTamas** [jawj/zapatos#85]
The exported types of `Selectable` `Insertable` etc. are interfaces. This means, that they do not have an index signature by default. Our team relies on extending generic Records. I can't use the interfaces, where an indexable record is expected.
Code example:

```
import type * as s from 'zapatos/schema';
type UnknownObject = Record<string, unknown>
const myFunction = <T extends UnknownObject>(arg: T): void => {}
const processDb = (): s.table.Insertable => {
  return {id: 10, name: 'myname'}
}
const someInsertable = processDb()
myFunction(someInsertable)
```

If the exported types were type synonyms (export type Selectable = ...) instead of interfaces, then calling `myFunction` with `someInsertable` would not produce the following error:
```
Argument of type 'Insertable' is not assignable to parameter of type 'UnknownObject'.
  Index signature is missing in type 'Insertable'.ts(2345)
```
Is there perhaps some configuration for the `zg.generate` function, that configures the schema to only  have type synonyms, and not interfaces?

Thanks in advance.

**Comment by jawj** [comment]
I'd prefer not to add an option for this. If it's an issue that many people turn out to have, I'd consider offering a type alias version as well as an interface version of the types under a different namespace.

Until or unless that happens, I can see a couple of possible workarounds.

The first is that you can convert `someInsertable` to a form that `myFunction` accepts by spreading it into a new object:

```typescript
myFunction({ ...someInsertable });  // no type errors here
```

The second is that you can convert any interfaces to a type alias using mapped types:

```
type MyInsertableTypeAlias = { [s in keyof s.table.Insertable]: s.table.Insertable[s] };

const processDbAlt = (): MyInsertableTypeAlias => {
  return { path: '/', created_at: new Date(), updated_at: new Date() };
}
const someTypeAlias = processDbAlt();
myFunction(someTypeAlias);  // no type errors here either
```

**Comment by RigoTamas** [comment]
Thanks for the quick response. These workarounds are fine, thanks for sharing them with me.
