### ISSUE TITLE
extras adds properties

### ISSUE THREAD

**Issue by puckey** [jawj/zapatos#87]
I was refactoring my code to use the new `extras` functionality as described in https://github.com/jawj/zapatos/issues/80 and noticed that it was returning both the original column name as well as the aliased one:

```js
  const places = await db
    .select('place', db.all, {
      columns: ['id'],
      extras: {
        abc: 'id'
      }
    })
    .run(pool);
```
returns
```js
[{"id":1,"abc":1}]
```
while I expected it to return
```js
[{"abc":1}]
```

I am not sure this functionality offers any upsides this way, since any use case that I can imagine would then mean mapping through the results to copy over just the `abc` property

**Comment by jawj** [comment]
Right: this is what I meant when I said:

> (Though you do need to specify the other columns if you don't want to also return all columns under their original names, as well as your renamed ones).

To get what you expected, give it an empty `columns` option instead:

```typescript
const places = await db
  .select('place', db.all, {
    columns: [],
    extras: {
      abc: 'id'
    }
  })
  .run(pool);  // returns [{"abc":1}]
```

**Comment by puckey** [comment]
Ahh understood! Sorry about that : )
