### ISSUE TITLE
The export name "__esModule" is reserved and cannot be used (it's needed as an export marker when converting ES module syntax to CommonJS)

### ISSUE THREAD

**Issue by moltar** [jawj/zapatos#92]
Getting the following error:

> The export name "__esModule" is reserved and cannot be used (it's needed as an export marker when converting ES module syntax to CommonJS)

https://github.com/jawj/zapatos/blob/43a27cab30085566bf7d109bb095bf3a52192272/generate.mjs#L4

When using `esbuild`.

I think probably related to this: https://github.com/evanw/esbuild/pull/1338

Any ideas?

**Comment by jawj** [comment]
Hmm. It's not immediately obviously to be whether this is a problem with [gen-esm-wrapper](https://github.com/addaleax/gen-esm-wrapper), which is run as the last build step, or with how we're using it here, or with esbuild itself.

**Comment by bjornstar** [comment]
This should be fixed with `gen-esm-wrapper@1.1.2`, could you give it a try?

**Comment by jawj** [comment]
Thanks @bjornstar, that certainly seems to get rid of the `__esModule` export.

**Comment by jawj** [comment]
This change is now published in 4.0.3.
