### ISSUE TITLE
Ambiguous column reference in `WHERE ${{ ... }}`

### ISSUE THREAD

**Issue by jgonera** [jawj/zapatos#94]
I'm trying to write a manual query (no helper functions) joining two tables that have a column with the same name, let's call it `dupe_column` (in reality it's a [`WITH RECURSIVE` query](https://www.postgresql.org/docs/13/queries-with.html), but I think the same would happen for a join between two regular tables):

```sql
SELECT * FROM ${'table_a'}
JOIN ${'table_b'}
ON ${'table_a'}.${'b_id'} = ${'table_b'}.${'id'}
WHERE ${{ dupe_column: dupeColumn }}
```
(`dupeColumn` is an argument of type `string`)

The problem with this is that I get `column reference "dupe_column" is ambiguous` from Postgres.

I tried replacing `WHERE ${{ dupe_column: 'something' }}` with `WHERE ${'table_a'}.${'dupe_column'} = ${dupeColumn}` but then Zapatos types complain:

```
Argument of type 'string' is not assignable to parameter of type '"id" | "created_at" | "updated_at" | "groups" | "groups_securities" | unique symbol | table_a.Whereable | table_b.Whereable | "user_id" | "name" | ... 11 more ... | SQLExpression[]'.
```

`WHERE ${{ 'table_a.dupe_column': dupeColumn }}` doesn't seem to do the trick either.

Is there any way to solve this?

**Comment by jawj** [comment]
Outside of a `Whereable` object, variables to be interpolated need to be wrapped like so:

`WHERE ${{ dupe_column: 'something' }} with WHERE ${'table_a'}.${'dupe_column'} = ${db.param(dupeColumn)}`

**Comment by jgonera** [comment]
That works! Sorry, I missed it in the docs.
